### ISSUE TITLE
Loclist is empty/makes vim crashes

### ISSUE THREAD

**Issue by VincentCordobes** [neoclide/coc.nvim#1034]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.0-dev
node version: v10.16.0
coc.nvim version: 0.0.73-b96f1d0e0b
term: iTerm.app
platform: darwin

## Messages

## Output channel: watchman

[Info  - 9:08:13 AM] watchman watching project: /Users/Vincent/tmp
[Info  - 9:08:13 AM] subscribing "**/.eslintr{c.js,c.yaml,c.yml,c,c.json}" in /Users/Vincent/tmp
[Info  - 9:08:13 AM] subscribing "**/.eslintignore" in /Users/Vincent/tmp
[Info  - 9:08:13 AM] subscribing "**/package.json" in /Users/Vincent/tmp
[Info  - 9:08:13 AM] subscribing "**/[tj]sconfig.json" in /Users/Vincent/tmp
[Info  - 9:08:13 AM] subscribing "**/package.json" in /Users/Vincent/tmp
[Info  - 9:08:13 AM] subscribing "**/*.ts" in /Users/Vincent/tmp
[Info  - 9:08:13 AM] subscribing "**/*.js" in /Users/Vincent/tmp

## Output channel: tsserver

[Info  - 9:08:13 AM] Forking TSServer
PATH: /Users/Vincent/.opam/4.07.1/bin:./node_modules/.bin:/Users/Vincent/.npm-global/bin:/Users/Vincent/scripts:/Users/Vincent/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:/opt/X11/bin:/usr/local/opt/fzf/bin 
[Info  - 9:08:13 AM] Started TSServer
{
  "path": "/Users/Vincent/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.5.1",
    "version": "3.5.1"
  }
}

## Output channel: eslint

[Info  - 9:08:13 AM] ESLint server running in node v10.16.0
[Info  - 9:08:14 AM] ESLint library loaded from: /Users/Vincent/.npm-global/lib/node_modules/eslint/lib/api.js


```

## Describe the bug

The loclist is empty and/or makes vim crash.

⚠️ After _git bisect_ it looks like ec3a954 is the first bad commit. `ec3a954^` is good.

## Reproduce the bug

- Create file `mini.vim` with：

```vim
set nocompatible
set runtimepath^=/path/to/coc.nvim
filetype plugin indent on
syntax on
set hidden
```

- Start (neo)vim with command: `vim -u mini.vim`

- write some bad code and open the loclist to see the error

## Screenshots

![neovim_loc_list](https://user-images.githubusercontent.com/7091110/62028892-b392a180-b1e1-11e9-8252-ad6091cf2b33.gif)

**Comment by chemzqm** [comment]
Looks like bug of your neovim.

**Comment by VincentCordobes** [comment]
I **can** reproduce with `Vim 8.1` and `NVIM v0.3.8`, the loclist is empty (We can see its content blinking for 0.01 s)

![vim](https://user-images.githubusercontent.com/7091110/62031744-61a14a00-b1e8-11e9-91ca-c473e5eca9a1.gif)

### NVIM v0.3.8 CocInfo
```
## versions

vim version: NVIM v0.3.8
node version: v10.16.0
coc.nvim version: 0.0.73-b96f1d0e0b
term: iTerm.app
platform: darwin

## Messages

## Output channel: watchman

[Info  - 9:59:37 AM] watchman watching project: /Users/Vincent/tmp
[Info  - 9:59:37 AM] subscribing "**/.eslintr{c.js,c.yaml,c.yml,c,c.json}" in /Users/Vincent/tmp
[Info  - 9:59:37 AM] subscribing "**/.eslintignore" in /Users/Vincent/tmp
[Info  - 9:59:37 AM] subscribing "**/package.json" in /Users/Vincent/tmp
[Info  - 9:59:37 AM] subscribing "**/[tj]sconfig.json" in /Users/Vincent/tmp
[Info  - 9:59:37 AM] subscribing "**/package.json" in /Users/Vincent/tmp
[Info  - 9:59:37 AM] subscribing "**/*.ts" in /Users/Vincent/tmp
[Info  - 9:59:37 AM] subscribing "**/*.js" in /Users/Vincent/tmp

## Output channel: tsserver

[Info  - 9:59:37 AM] Forking TSServer
PATH: /Users/Vincent/.opam/4.07.1/bin:./node_modules/.bin:/Users/Vincent/.npm-global/bin:/Users/Vincent/scripts:/Users/Vincent/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:/opt/X11/bin:/usr/local/opt/fzf/bin 
[Info  - 9:59:37 AM] Started TSServer
{
  "path": "/Users/Vincent/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.5.1",
    "version": "3.5.1"
  }
}

## Output channel: eslint

[Info  - 9:59:37 AM] ESLint server running in node v10.16.0
[Info  - 9:59:38 AM] ESLint library loaded from: /Users/Vincent/.npm-global/lib/node_modules/eslint/lib/api.js
```

### Vim 8.1 CocInfo
```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 12 2019 19:31:20)
node version: v10.16.0
coc.nvim version: 0.0.73-b96f1d0e0b
term: iTerm.app
platform: darwin

## Messages
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"test.js" 3L, 39C

E492: Not an editor command: CoCInfo
E492: Not an editor command: cocinfo
## Output channel: watchman

[Info  - 9:59:04 AM] watchman watching project: /Users/Vincent/tmp
[Info  - 9:59:04 AM] subscribing "**/.eslintr{c.js,c.yaml,c.yml,c,c.json}" in /Users/Vincent/tmp
[Info  - 9:59:04 AM] subscribing "**/.eslintignore" in /Users/Vincent/tmp
[Info  - 9:59:04 AM] subscribing "**/package.json" in /Users/Vincent/tmp
[Info  - 9:59:04 AM] subscribing "**/[tj]sconfig.json" in /Users/Vincent/tmp
[Info  - 9:59:04 AM] subscribing "**/package.json" in /Users/Vincent/tmp
[Info  - 9:59:04 AM] subscribing "**/*.ts" in /Users/Vincent/tmp
[Info  - 9:59:04 AM] subscribing "**/*.js" in /Users/Vincent/tmp

## Output channel: tsserver

[Info  - 9:59:04 AM] Forking TSServer
PATH: /Users/Vincent/.opam/4.07.1/bin:./node_modules/.bin:/Users/Vincent/.npm-global/bin:/Users/Vincent/scripts:/Users/Vincent/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:/opt/X11/bin:/usr/local/opt/fzf/bin 
[Info  - 9:59:04 AM] Started TSServer
{
  "path": "/Users/Vincent/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.5.1",
    "version": "3.5.1"
  }
}

## Output channel: eslint

[Info  - 9:59:04 AM] ESLint server running in node v10.16.0
[Info  - 9:59:05 AM] ESLint library loaded from: /Users/Vincent/.npm-global/lib/node_modules/eslint/lib/api.js
```

**Comment by chemzqm** [comment]
Should be fixed now.

**Comment by VincentCordobes** [comment]
Still have an empty loclist. Is there anything I can do apart from staying on `ec3a954^`?

**Comment by chemzqm** [comment]
use latest release,checkout CocInfo

**Comment by VincentCordobes** [comment]
6d4508c3660373331383848e15820a8c940d028f did fix it 👍
