### ISSUE TITLE
Extra whitespace before completion

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#153]
**Describe the bug**

Member completion, at least for clangd, is coming with leading whitespace.

**To Reproduce**
1. configure with
   ```json
   {
     "languageserver": {
       "clangd": {
         "command": "clangd",
         "filetypes": ["c", "cpp", "objc", "objcpp"]
       }
     }
   }
   ```
2. Complete after `s.` in the following code:
   ```
   #include <iostream>
   
   struct S {
       int x;
       int y;
       int foo(int x, int y);
       int foo(int a, int b, int c);
   };
   
   int main() {
       S s;
       s.
   }
   ```

**Expected behavior**
No leading whitespace for completion items.

**Screenshots**
![04 52 18_08-11-18](https://user-images.githubusercontent.com/1269815/48182409-2d13f800-e312-11e8-8160-06a9624727a3.png)

**Desktop (please complete the following information):**
 - Terminal: Termite
 - Version: v13

**Additional context**
After a completion item is selected and confirmed, the leading whitespace gets removed, which cause a weird jagged effect.

**Comment by chemzqm** [comment]
I can't reproduce it.
Consider add `"trace.server": "verbose"` to `clangd` section and upload the output from clangd.
https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Looks like clangd return completion item with extra space ahead in label, coc use label as insertText for snippet, it could be improved.

**Comment by chemzqm** [comment]
Fixed at https://github.com/neoclide/coc.nvim/commit/50afb7e92f25bd3d06711cd40bbd08110ec52d6e, try master branch by use `yarn install`

**Comment by oblitum** [comment]
@chemzqm thanks, that fixed the insertion text but the menu seems to still contain them, so I think it's still not fully fixed.

**Comment by oblitum** [comment]
Or maybe it's done on purpose and I'm not seeing the benefit.

**Comment by oblitum** [comment]
After this update an issue was introduced, the menu now is missing completions that were previously provided:

![13 09 20_08-11-18](https://user-images.githubusercontent.com/1269815/48207411-b8fc4300-e357-11e8-860c-f860a9cd012f.png)

**Comment by chemzqm** [comment]
I see, looks like I should not split the insertText.
