### ISSUE TITLE
[help] Auto complete floating window doesn't disappear when pressing ESC

### ISSUE THREAD

**Issue by waldemarnt** [neoclide/coc.nvim#1940]
Looks like my auto-complete floating window only disappear when I type something if I press ESC, for example, it stays there forever.

![preview](https://i.ibb.co/71pCBBG/Screen-Shot-2020-05-17-at-3-56-26-pm.png)

**Environment**
vim version: NVIM v0.5.0-5f92093
node version: v12.16.3
coc.nvim version: 0.0.78-d83536aa4e
term: iTerm.app
platform: darwin

[my .vimrc](https://github.com/waldemarnt/dotfiles/blob/master/.vimrc)

Any idea how can I make it hide for when pressing sec?

**Comment by waldemarnt** [comment]
Just found out that it has been discussed here already https://github.com/neoclide/coc.nvim/issues/531 and looks like it's happening to more people, in the meantime I mapped `:call coc#util#float_hide()` to my ESC

**Comment by chemzqm** [comment]
It should be hidden on CompleteDone

**Comment by waldemarnt** [comment]
thansk @chemzqm is it a coc config? can you point me to an example please?

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

**Comment by a-torgovitsky** [comment]
I am still encountering this problem occasionally. I am not sure how to reproduce it reliably though...
Not very helpful, sorry.

**Comment by chemzqm** [comment]
Upgrade to latest release branch of coc.nvim

**Comment by a-torgovitsky** [comment]
I was already pretty current. Just updated again and these are the new commits I was missing:
```vim
* f143e53 fix(handler): fix filetype of signature help (5 hours ago)
* 1d2bf0c chore(package): improve package.json for release branch (5 hours ago)
* fe2f462 fix(util): check winid for coc#util#close_win (16 hours ago)
* 6b7767f fix(workspace): avoid neovim's address error with bd! (28 hours ago)
```
is this one related?
```vim
* fe2f462 fix(util): check winid for coc#util#close_win (16 hours ago)
```

**Comment by chemzqm** [comment]
Try upgrade your vim or provide reproduce way.

**Comment by a-torgovitsky** [comment]
nvim v0.4.3

I will let you know if I find a way to reproduce
So far I haven't been able to figure out the pattern
