### ISSUE TITLE
Jump to next/prev entry in CocList

### ISSUE THREAD

**Issue by piersy** [neoclide/coc.nvim#2087]
**Is your feature request related to a problem? Please describe.**

I'm used to using the quickfix window to show locations and navigate through them with the keys `<c-l>` `<c-h>` mapped to `:cnext` and `:cprev` . This this allows me to easily skip backwards and forwards through the list entries, each time placing my cursor in my current editing window at the location defined by the list entry (ie ready to make changes to the source). I often skip through a few entries make a change and then keep on skipping.  It's useful to have the quickfix open during this as it gives me an overview of all the locations.

By contrast using the list provided by coc-references throws up a preview window showing the location defined by the list entry and to actually go to that location you need to press `<enter>`, the problems with this are:

* The preview window is small so limits your view of the surrounding code
* An extra keypress is required to actually navigate to the code
* Pressing enter to navigate to the code jumps from the preview window to the main window, which is a slightly jarring transition since the cursor location changes on screen.
* Pressing enter to get to the code closes the list so you have to reopen it to continue

**Describe the solution you'd like**

I'd like to be able to map a key that navigates my main view to the next or previous list entry, which doesn't close the list and updates the highlighted list element. 

**Describe alternatives you've considered**

I know that you can use `:CocNext` and `:CocPrev`, I tried mapping them in the list mappings, but they close the list. I also tried setting `coc.preferences.useQuickfixForLocations` but that only works for locations so I end up dealing with a completely different interface to view references as opposed to document symbols.

**Comment by chemzqm** [comment]
``` vim
let g:coc_enable_locationlist = 0
autocmd User CocLocationsChange CocList -no-quit --first --normal location
```

``` json
  "list.normalMappings": {
    "<C-j>": "command:CocNext",
    "<C-k>": "command:CocPrev",
  },
```

**Comment by piersy** [comment]
Hi @chemzqm thanks for the quick response.

That setup almost works but jumping to an entry doesn't leave my cursor at the location defined by the entry in the list, instead my cursor always remains held in the command bar. This has the following consequences.

* I can't easily see what has been jumped to, since there is no highlight and no cursor in the main window.
* I still need an extra key-press to navigate to the code (now it's `<esc>`)
* Pressing `<esc>` closes the list, this prevents easily jumping to a location doing some editing and then jumping to the next location.

It's not clear to me what kind of construct coc list is in vim terms, could you explain a bit about how the cursor is held in the command bar and why we need to configure mappings for it in coc-settings.json rather than using the normal approach.

I think a simpler way to describe the functionality im looking for would be exactly the functionality provided by `:CocNext` and `:CocPrev` with the default list settings, but just keeping the list open.

I'd also like to be able to switch between the list and my main window, so that I could for instance:

1. Search for referencess
1. Jump through them (with the cursor being placed in the main window)
1. Edit something in the main window 
1. Switch back to the list, filter it a bit
1. Continue jumping through the entries

**Comment by chemzqm** [comment]
You can configure coc.nvim use vim's quickfix list which is what you need

**Comment by chemzqm** [comment]
I've made it not focus list window after action, should be what you've expected.

**Comment by piersy** [comment]
Hi @chemzqm thanks for the update.

With your update coc list is working almost as I was hoping.

There are still a couple of problems though.

* Jumping to elements in the list seems to set the `scrolloff` to 0 for the buffer that is the target of the list entry to 0.
* The list does not update to reflect the last jumped to location, but then seems to malfunction when you reach the entry at the bottom of the list buffer and the list starts to scroll. See attached gif, where I find references and then just keep invoking CocNext.

![CocListUpdateBug](https://user-images.githubusercontent.com/5087847/85283549-77b19c00-b485-11ea-9e4d-7f2436fc7036.gif)

**Comment by piersy** [comment]
Hi @chemzqm having used the new coc list functionality today, I realise now, for the new list to be useful it needs an easy way for the list to be closed.

Currently the only way I have found to close the list is to move back to the list window and use `<esc>`.

**Comment by chemzqm** [comment]
> Jumping to elements in the list seems to set the scrolloff to 0 for the buffer that is the target of the list entry.

I can't  reproduce.

> The list does not update to reflect the last jumped to location, but then seems to malfunction and highlight each entry persistently when you reach the entry at the bottom of the list buffer and the list starts to scroll. 

Can't reproduce, try minimal vimrc.

**Comment by chemzqm** [comment]
Changed to list cancel exist session when necessary, you can create your key-mapping to close the list window.

**Comment by piersy** [comment]
Hi @chemzqm 

>Changed to list cancel exist session when necessary

Thanks, I can see the list gets repopulated when I execute another list operation.

> you can create your key-mapping to close the list window.

Could you elaborate, I can't see any command or function to close the list, so I don't know what I would map to?

Here is a minimal vimrc with which I can reproduce the problems I mentioned above. Although I realise now the scrolloff is set to 0 just by opening the list.

I'm running NVIM v0.4.3 with master at 263ec93b2c32e9ba8912d7dedf5565b1d80e6ab7

```vim
call plug#begin()

Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}

call plug#end()

let mapleader = "\<Space>"

" coc nvim suggests these settings

" Some servers have issues with backup files, see #649
set nowritebackup
set nobackup
" Better display for messages
set cmdheight=2

" You will have bad experience for diagnostic messages when it's default 4000.
set updatetime=300

" don't give |ins-completion-menu| messages.
set shortmess+=c

" always show signcolumns
set signcolumn=yes


let g:coc_enable_locationlist = 0
autocmd User CocLocationsChange CocList --no-quit --normal location

nmap <leader>u <Plug>(coc-references)
nnoremap <c-l> :CocNext<cr>
nnoremap <c-h> :CocPrev<cr>

```

**Comment by chemzqm** [comment]
Fixed scrolloff by 551353208df1c1d62a476a8cd721dd35eb80f8c5

**Comment by piersy** [comment]
Hi @chemzqm 5513532 fixed setting the scrolloff to 0 but the selected CocList entry is still not correctly updated when I invoke CocNext/Prev from my bindings.

**Comment by chemzqm** [comment]
I've confirmed the highlight issue is bug of neovim, happens on master as well

**Comment by chemzqm** [comment]
Don't have time to create yet.

**Comment by Shellcat-Zero** [comment]
@piersy were you able to find a resolution to your issue? I have not been able to figure out how to keep the references pane open while continuing to edit a file. I can switch panes with ctrl+ww but I cannot seem to do any editing, and then selecting a file from the references pane also closes the reference pane while it opens the selected file in buffer, but what I want is for the references pane to stay open and just change/update depending on when I hit 'gr' to find a new reference. Is any of this accomplished in your vimrc above?
