### ISSUE TITLE
"E315: ml_get: invalid lnum" when pasting text copied blockwise

### ISSUE THREAD

**Issue by tomtomjhj** [neoclide/coc.nvim#2227]
### `:version`
(latest version from nightly PPA)
```
NVIM v0.5.0-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-1nw4c4/neovim-0.5.0+ubuntu1+git202008031341-4ed5204-00e710e=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-1nw4c4/neovim-0.5.0+ubuntu1+git202008031341-4ed5204-00e710e/build/config -I/build/neovim-1nw4c4/neovim-0.5.0+ubuntu1+git202008031341-4ed5204-00e710e/src -I/build/neovim-1nw4c4/neovim-0.5.0+ubuntu1+git202008031341-4ed5204-00e710e/.deps/usr/include -I/usr/include -I/build/neovim-1nw4c4/neovim-0.5.0+ubuntu1+git202008031341-4ed5204-00e710e/build/src/nvim/auto -I/build/neovim-1nw4c4/neovim-0.5.0+ubuntu1+git202008031341-4ed5204-00e710e/build/include
Compiled by buildd@lcy01-amd64-003

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

### `:checkhealth`
```
health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle build/index.js found
  - OK: Service started

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='6003'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0
  - INFO: Checking stuff
  - WARNING: `focus-events` is not enabled. |'autoread'| may not work.
    - ADVICE:
      - (tmux 1.9+ only) Set `focus-events` in ~/.tmux.conf:
          set-option -g focus-events on
  - INFO: $TERM: tmux-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.8.2
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v10.19.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - WARNING: `perl` and `cpanm` must be in $PATH.
    - ADVICE:
      - Install Perl and cpanminus and verify that `perl` and `cpanm` commands work.
```

### `:CocInfo`
```
vim version: NVIM v0.5.0-dev
node version: v10.19.0
coc.nvim version: 0.0.78-0ff42027ff
coc.nvim directory: ~/.vim/plugged/coc.nvim
term: tmux-256color
platform: linux
```

## Describe the bug
Neovim produces `E315: ml_get: invalid lnum` error when pasting the text copied blockwise beyond the eof.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `nvim -u mini.vim`

- steps to reproduce
  1. enter following text (`i1<CR>2<ESC>`)
     ```
     1
     2
     ```
  2. copy it blockwise (`y<C-v>k`)
  3. paste after `2` (`jp`)
     ```
     1
     21
      2
     ```
  4. `E315: ml_get: invalid lnum: 4`!

## note
This bug reproduces in nvim v0.3.2 (coc.nvim minimal requirment).
I couldn't reproduce this in Vim v8.2.1149.

These are recent vim patches that mentions `ml_get` in the commit title. The checked ones are ported to Neovim.  My impression is that patch that are not ported to Neovim are not relevant to this issue.  So this probably is a Neovim problem. However, I'm posting this here since I couldn't make the minimal input to reproduce this issue without coc.nvim.

* [ ] 8.2.0614: get ml_get error when deleting a line in 'completefunc'
* [x] 8.1.2363: ml_get error when accessing Visual area in 'statusline'
* [x] 8.1.2236: ml_get error if pattern matches beyond last line
* [x] 8.1.2223: cannot see what buffer an ml_get error is for
* [x] 8.1.1932: ml_get errors after using append()
* [x] 8.1.1890: ml_get error when deleting fold marker
* [x] 8.1.1045: E315 ml_get error when using Python and hidden buffer
* [x] 8.1.0786: ml_get error when updating the status line
* [x] 8.1.0511: ml_get error when calling a function with a range
* [ ] 8.1.0499: :2vimgrep causes an ml_get error
* [x] 8.1.0458: ml_get error and crash when using "do"
* [ ] 8.1.0425: ml_get error and crash with appendbufline()
* [ ] 8.1.0171: typing CTRL-W n in a terminal window causes ml_get error
* [ ] 8.0.1684: ml_get errors when using terminal window for shell command
* [x] 8.0.0762: ml_get error with :psearch in buffer without a name
* [x] 8.0.0515: ml_get errors in silent Ex mode
* [ ] 8.0.0271: may get ml_get error when :tcldo deletes lines
* [ ] 8.0.0270: may get ml_get error when :rubydo deletes lines
* [ ] 8.0.0269: may get ml_get error when :perldo deletes lines
* [ ] 8.0.0268: may get ml_get error when :luado deletes lines
* [x] 8.0.0265: may get ml_get error when :pydo deletes lines

**Comment by fannheyward** [comment]
Reproduced with coc.nvim

**Comment by chemzqm** [comment]
Should be problem with neovim's buffer events `:h api-buffer-updates`

**Comment by tomtomjhj** [comment]
@chemzqm Thanks. Indeed, this bug is triggered when nvim sends the buffer updates to coc. I'll post some updates on https://github.com/neovim/neovim/issues/12718 soon.

**Comment by tomtomjhj** [comment]
Fixed by https://github.com/neovim/neovim/pull/12733

**Comment by amirongit** [comment]
> Fixed by [neovim/neovim#12733](https://github.com/neovim/neovim/pull/12733)

it's not fixed I have the exact same issue. same re-producing process.
