### ISSUE TITLE
How to properly use coc_uri_prefix_replace_patterns under MSYS2?

### ISSUE THREAD

**Issue by xubury** [neoclide/coc.nvim#2563]
When running vim under msys2, it shows a warning:`g:coc_cygqwin_path_prefixes is deprecated, use g:coc_uri_prefix_replace_patterns
 instead`
And the coc command etc doesn't work.
`[coc.nvim] Error on "CocList lists": ENOENT: no such file or directory, stat '\c\Users\Bury\.config\coc'`

So I thought it's the cygwin path's fault and set `g:coc_uri_prefix_replace_patterns ` like below:
`let g:coc_uri_prefix_replace_patterns = {'\c\': 'C:\'}`

But still, it shows the same error and warnings. How can I properly configure it?

OS:windows 10
vim:8.2
shell:msys2-mingw

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

**Comment by xubury** [comment]
```
2020-11-08T13:17:30.158 ERROR (pid:16612) [extensions] - Error on active extension coc-snippets: Error: ENOENT: no such file or directory, mkdir 'C:\c\Users\Bury\.config\coc\ultisnips' [Error: ENOENT: no such file or directory, mkdir 'C:\c\Users\Bury\.config\coc\ultisnips'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'C:\\c\\Users\\Bury\\.config\\coc\\ultisnips'
}
```
@chemzqm  hi, thanks for the quick fix . The warning is gone. But I still getting the weird cygwin path and I can't use CocCommand. How can I fix this with `g:coc_uri_prefix_replace_patterns`?

```
vim version: VIM - Vi IMproved 8.2 8021895
node version: v15.1.0
coc.nvim version: 0.0.79-be822b546f
coc.nvim directory: C:\Users\Bury\AppData\Local\nvim\plugged\coc.nvim
term: mintty
platform: win32
```

**Comment by chemzqm** [comment]
Not all paths are fixed, we don't have good support for cygwin for now

**Comment by Meursau1T** [comment]
Try to add this to .vimrc ?
```
let g:coc_data_home = 'C:\\Users\\Bury\\.config\\coc'
```

**Comment by xietren** [comment]
I think the reason is that coc-snippets does not support cygwin or msys2. I get a temporary method to get snippets.

First, to override the error report.
set g:coc_data_home the same as the absolute path which coc.nvim uses . For example，
let g:coc_data_home="D:/msys64/home/username/.config/coc"
