### ISSUE TITLE
[coc.nvim] Can't create tmp file: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by ggarnier** [neoclide/coc.nvim#2589]
## Result from CocInfo

```
vim version: NVIM v0.4.0-944-g3305769ea
node version: v12.3.1
coc.nvim version: 0.0.79
coc.nvim directory: /home/myself/.config/nvim/plugged/coc.nvim
term: screen-256color
platform: linux

## Log of coc.nvim

2020-11-11T19:29:46.836 INFO (pid:6359) [services] - registered service "eslint"
2020-11-11T19:29:46.839 INFO (pid:6359) [plugin] - coc.nvim 0.0.79 initialized with node: v12.3.1 after 67ms
```

## Describe the bug

After installing `coc.nvim`, I get this error message when starting `nvim`:

```
[coc.nvim] Can't create tmp file: The "path" argument must be of type string. Received type undefined
```

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  call plug#begin()
  Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}
  call plug#end()
  ```

- Start (neo)vim with command: `vim -u mini.vim`

## Screenshots (optional)

![Screenshot from 2020-11-11 18-37-45](https://user-images.githubusercontent.com/86251/98867276-0e8aef00-244d-11eb-8b61-6b030666128f.png)

**Comment by chemzqm** [comment]
It was fixed.

**Comment by ggarnier** [comment]
@chemzqm I've just updated both `neovim` and `coc.nvim`, but I still see this error message. Could you link where the fix, or anything that could help me debug this?

**Comment by sebosp** [comment]
In my case,  running export TMPDIR="/tmp" fixed it, somehow wasn't set for my shell.

**Comment by shaul75** [comment]
Same happens to me. 
NVIM v0.4.4

**Comment by saketverma-03** [comment]
if you are using "zsh shell" then add "export TMPDIR="/tmp" <without quots>  to your ".zshrc" file
-> then save and close terminal
and from next time you open nvim there shouldnt be that error, i did this an it worked for me

**Comment by shaul75** [comment]
> if you are using "zsh shell" then add "export TMPDIR="/tmp" to your ".zshrc" file
> -> then save and close terminal
> and from next time you open nvim there shouldnt be that error, i did this an it worked for me
doesn't change anything in my case
~ >>> echo $TMPDIR                                                                                                                 
/tmp
and still getting:
[coc.nvim] Can't create tmp file: The "path" argument must be of type string. Received undefined

**Comment by sebosp** [comment]
@shaul75 , can you please share OS, distro, are you maybe using cygwin ? 
Also could you provide the output to the following cammands ?
```bash
$ node --version
$ echo $TMPDIR
$ node -e 'console.log(process.env)'|grep -i tmp
```

**Comment by shaul75** [comment]
@sebosp Thanks.
OS: Manjaro Linux x86_64
Kernel: 5.8.18-1-MANJARO
Shell: zsh 5.8
coc.nvim: Already up to date.
```
~ >>> node --version                                                                                                                                                                                                                  
v14.15.0
~ >>> echo $TMPDIR                                                                                                                                                                                                                    
/tmp
~ >>> node -e 'console.log(process.env)'|grep -i tmp                                                                                                                                                                                  
SESSION_MANAGER: 'local/heartofgold:@/tmp/.ICE-unix/1894,unix/heartofgold:/tmp/.ICE-unix/1894',
```

**Comment by sebosp** [comment]
@shaul75 you might be missing an `export` in your shell config (zshrc I guess).
For example, only after explicit export can I have another exec (i.e. node) see the TMPDIR variable:
```bash
amon% echo $TMPDIR

amon% node -e 'console.log(process.env.TMPDIR)' # Nothing is set yet, we expect undefined
undefined
amon% TMPDIR="/tmp"
amon% node -e 'console.log(process.env.TMPDIR)' # Variable is defined but not exported, would not be sent over to 'node', so it is still undefined for the process context
undefined
amon% export TMPDIR="/tmp"
amon% node -e 'console.log(process.env.TMPDIR)' # Finally variable is exported and would be presented over to 'node'
/tmp
```

**Comment by okmanideep** [comment]
The issue was fixed after I updated node (pointed) to v14.x

**Comment by chemzqm** [comment]
coc.nvim using `setenv` for `TMPDIR` environment variable, I don't know how could the issue happens.

**Comment by saketverma-03** [comment]
> > if you are using "zsh shell" then add "export TMPDIR="/tmp" to your ".zshrc" file
> > -> then save and close terminal
> > and from next time you open nvim there shouldnt be that error, i did this an it worked for me
> 
> doesn't change anything in my case
> ~ >>> echo $TMPDIR
> /tmp
> and still getting:
> [coc.nvim] Can't create tmp file: The "path" argument must be of type string. Received undefined

check your ".bashrc or .zshrc" or for whichever shell you are using make shure it has " exports TMPDIR = "/tmp" "
i dont know about the error but this is what i did and it works, im new to linux so dont no muxh details of error.

**Comment by ggarnier** [comment]
`export TMPDIR="/tmp"` also fixed for me (I'm using bash). Thanks everyone!

**Comment by 2lu3** [comment]
hi
I'm facing same problem.

## My problem
When I run `CocInstall coc-tsserver`, the error message was displayed. 
```
[coc.nvim] Can't create tmp file: The "path" argument must be of type string. Received undefined
and
Install finished
- x coc-tsserver /snap/bin/npm install exited with 243
```

And I run these commands and the results are below.
```bash
$ echo $TMPDIR
/tmp

$ node -e 'console.log(process.env.TMPDIR)'
undefined

$ export TMPDIR="/tmp"

$ node -e 'console.log(process.env.TMPDIR)'
undefined

$ tail .bashrc
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export NODE_PATH=/usr/local/lib/node_modules
export TMPDIR=~/tmp

$ ls -l
total 16
drwxrwxr-x 6 xxx xxx 4096 Apr  5 10:39 community
drwxr-xr-x 3 xxx xxx4096 Apr  4 15:22 snap
-rw-rw-r-- 1 xxx xxx 2317 Apr  5 11:06 test
drwxrwxr-x 2 xxx xxx 4096 Apr  5 11:01 tmp

$ source .bashrc

$ node -e 'console.log(process.env.TMPDIR)'
undefined 
```

Please give me a help

## My environment
 * Ubuntu 20.04.2 LTS
 * nvim v0.4.4
 * node v14.16.0

### check health
```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $SSH_TTY='/dev/pts/0'

health#provider#check
========================================================================
## Clipboard (optional)
  - WARNING: No clipboard tool found. Clipboard registers (`"+` and `"*`) will not work.
    - ADVICE:
      - :help |clipboard|

## Python 2 provider (optional)
  - INFO: pyenv: Path: /home/tlaloc/.pyenv/libexec/pyenv
  - INFO: pyenv: Root: /home/tlaloc/.pyenv
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /home/tlaloc/.pyenv/shims/python does not exist: pyenv: python: command not found

          The `python' command exists in these Python versions:
          3.9.3
          3.9.3/envs/neovim
          neovim

          Note: See 'pyenv help global' for tips on allowing both
          python2 and python3 to be found.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: pyenv: Path: /home/tlaloc/.pyenv/libexec/pyenv
  - INFO: pyenv: Root: /home/tlaloc/.pyenv
  - INFO: Using: g:python3_host_prog = "/home/tlaloc/.pyenv/versions/neovim/bin/python"
  - INFO: Executable: /home/tlaloc/.pyenv/versions/neovim/bin/python
  - INFO: Python version: 3.9.3
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v14.16.0
  - INFO: Neovim node.js host: /home/tlaloc/.config/yarn/global//node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.9.0
```

**Comment by hal256** [comment]
I updated nodejs to v15.13.0 and the error went away.

**Comment by 2lu3** [comment]
Thank you!

**Comment by vogler** [comment]
`export TMPDIR="/tmp"` does not fix it for me.

**Comment by hesxenon** [comment]
this seems like a bug with node v14.15.x to me, using nvm to load both versions and `node -e 'console.log(process.env.TMPDIR)'` gives `undefined` with 14.15.x and `/tmp` with 14.17.x. Didn't find anything in their changelogs related to env variables though...

```shell
$ export TMPDIR=/tmp
$ node -v
14.17.1
$ node -e 'console.log(process.env.TMPDIR)'
/tmp
$ nvm use 14.15
Now using node v14.15.4 (npm v6.14.10)
$ node -e 'console.log(process.env.TMPDIR)'
undefined
```

**Comment by vogler** [comment]
```console
$ export TMPDIR=/tmp
$ echo $TMPDIR
/tmp
$ node -v
v16.4.1
$ node -e 'console.log("TMPDIR:", process.env.TMPDIR)'
TMPDIR: 
```
@chemzqm reopen as there's no fix?

**Comment by vogler** [comment]
Also, in which commit was this supposed to be fixed?
I tried to find where this error comes from, but seems hard to search for.
Error on startup: `[coc.nvim] Can't create tmp file: The "path" argument must be of type string. Received undefined`
Inside nvim afterwards:
```vim
:echo $TMPDIR
/tmp
:echo fnamemodify(tempname(), ':p:h')
/tmp/nvimxrK219
```
https://github.com/neoclide/coc.nvim/blob/a3966628cb090ed9a102e7b9c78f9fb90abffd21/autoload/coc/client.vim#L46

**Comment by chemzqm** [comment]
> ```
> $ export TMPDIR=/tmp
> $ echo $TMPDIR
> /tmp
> $ node -v
> v16.4.1
> $ node -e 'console.log("TMPDIR:", process.env.TMPDIR)'
> TMPDIR: 
> ```
> 
> @chemzqm reopen as there's no fix?

Can't reproduce with node v16.4.1

**Comment by vogler** [comment]
> Can't reproduce with node v16.4.1, please provide your vim version.

Can't reproduce the empty `node -e 'console.log(process.env.TMPDIR)'`? Then the vim version should not matter, no?

```console
$ nvim --version
NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-PpSRXj/neovim-0.3.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-PpSRXj/neovim-0.3.4/build/config -I/build/neovim-PpSRXj/neovim-0.3.4/src -I/usr/include -I/build/neovim-PpSRXj/neovim-0.3.4/build/src/nvim/auto -I/build/neovim-PpSRXj/neovim-0.3.4/build/include
Compiled by team+vim@tracker.debian.org
Features: +acl +iconv -jemalloc +tui
$ lsb_release -a
Description:    Raspbian GNU/Linux 10 (buster)
```
There's no newer version available in Debian stable: https://packages.debian.org/search?keywords=neovim

**Comment by fannheyward** [comment]
```sh
❯ node --version
v16.4.2

❯ export TMPDIR=/tmp
❯ node -e 'console.log(process.env.TMPDIR)'
/tmp
```

**Comment by vogler** [comment]
```console
$ env | grep TMPDIR
TMPDIR=/tmp
$ node -e 'child_process.exec("env", console.log)' | grep TMPDIR

```
I have `export TMPDIR=/tmp` in my `.zshenv`, but it seems like node does not pick it up (but it shows other variables set there).
Can't reboot now, but maybe it takes the old env from some running node process, tmux session or whatever. Very strange.

Can't you just use `/tmp` as a fallback if `TMPDIR` is not set? No other program I have installed needs `TMPDIR` to be set.

**Comment by chemzqm** [comment]
It seems bug with your vim since TMPDIR is passed env with jobstart function, try update your vim and coc.nvim or provide your CocInfo

**Comment by vogler** [comment]
> It seems bug with your vim since TMPDIR is passed env with jobstart function, try update your vim and coc.nvim or provide your CocInfo with minimal vimrc to reproduce

`:ConInfo` does not work due to the error.
nvim 0.3.4: https://github.com/neoclide/coc.nvim/issues/2589#issuecomment-876316264

I just updated coc.nvim (acc2b95be6652d79f86d586e52c7566557608476):
```console
pi@rpi3 ~/.vim/bundle/coc.nvim release
❯ git show
commit acc2b95be6652d79f86d586e52c7566557608476 (HEAD -> release, origin/release, origin/HEAD)
Author: Qiming Zhao <chemzqm@gmail.com>
Date:   Fri Jul 9 19:34:58 2021 +0800
```

Now I get an additional error before nvim opens:
```console
$ nvim .vimrc
Error detected while processing function coc#rpc#start_server[17]..<SNR>64_start:
line   51:
E117: Unknown function: getenv
E15: Invalid expression: { 'NODE_NO_WARNINGS': getenv('NODE_NO_WARNINGS'), 'TMPDIR': getenv('TMPDIR'), }
Press ENTER or type command to continue
```

**Comment by vogler** [comment]
Just installed a current nvim via [snap](https://snapcraft.io/install/nvim/raspbian):
```console
$ /snap/bin/nvim --version
NVIM v0.4.4
```
This gets rid of the `Unknown function: getenv` error on startup, but I still get the `[coc.nvim] Can't create tmp file: ...`.
