### ISSUE TITLE
Uncaught exception: Invalid channel name "languageserver.clangd0". only word characters and white space allowed

### ISSUE THREAD

**Issue by bigwudan** [neoclide/coc.nvim#2661]
win10环境，  提示 Uncaught exception: Invalid channel name "languageserver.clangd0". only word characters and white space allowed

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

**Comment by itsay3** [comment]
I'm using spacevim on mac osx, and I have the same problem. I have tried update with `SPupdate` and `SPReinstall coc.nvim` but the issue persists.
