### ISSUE TITLE
Completion causes cursor to vanish in Vim

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#290]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.

```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec  8 2018 11:23:48)
node version: v11.5.0
coc.nvim version: 0.0.40
term: dumb
platform: linux

## Error messages

## Output channel: prettier
```

**Describe the bug**

Completion in Vim is a bit flaky/flickered compared to NeoVim, and it causes the cursor vanish, while that never happens in NeoVim.

**To Reproduce**

1. Just type with completion in Vim.

**Screenshots**

![simplescreenrecorder](https://user-images.githubusercontent.com/1269815/50256613-3fd41f00-03de-11e9-9713-ed6cfda83aad.gif)

**Comment by chemzqm** [comment]
I have send `redraw` to vim after `TextChangeP`, so I don't know the why cursor become hidden.
I think it's bug of vim.

**Comment by oblitum** [comment]
This has been fixed recently, not happening anymore. Could you say which commit affected that?

**Comment by chemzqm** [comment]
It still happens when you change selected complete item, I don't know why.

**Comment by oblitum** [comment]
> I have send `redraw` to vim after `TextChangeP`, so I don't know the why cursor become hidden.
> I think it's bug of vim.

This is confirming that suspicion: https://github.com/w0rp/ale/issues/1470

**Comment by oblitum** [comment]
> This is confirming that suspicion: [w0rp/ale#1470](https://github.com/w0rp/ale/issues/1470)

That blames old Vim for the issue but I'm at [8.1.0570](https://github.com/vim/vim/releases/tag/v8.1.0570) from 18 days back and still have the issue.

**Comment by chemzqm** [comment]
It's not related.

**Comment by oblitum** [comment]
Nice! 🎉
