### ISSUE TITLE
Unregister before register capability with same id

### ISSUE THREAD

**Issue by kit494way** [neoclide/coc.nvim#2981]
**Is your feature request related to a problem? Please describe.**

When receive multiple `client/registerCapbility` requests with same id, duplicate completion sources are registered like the issue https://github.com/coc-extensions/coc-omnisharp/issues/53 .

**Describe the solution you'd like**

Call `feature.unregister(registration.id)` before this
https://github.com/neoclide/coc.nvim/blob/4e3b7f34da59aaa2753b1363fdbe8f08c75a6157/src/language-client/client.ts#L4124

**Describe alternatives you've considered**

**Additional context**

**Comment by chemzqm** [comment]
Should be fixed by d9092b72

**Comment by kit494way** [comment]
It looks like the issue is not fixed.

When language server retry to send a `client/registerCapability` request, language client receive multiple requests with same registration id.
`registerLanguageProvider()` method is called whether the request with same id is already handled or not, although the registration is managed by the id.
https://github.com/neoclide/coc.nvim/blob/531f5af61fa59d373cd73295341e396cb91f68a1/src/language-client/client.ts#L1726-L1727

In the situation that requests with same id are received, it may be something wrong with language server, but it is helpful to unregister the provider before register with same id or drop the request.

**Comment by Nazeehe** [comment]
I am unclear as to if this issue is fixed or not. The issue is closed, but I am seeing from the post above that it might not be?
