### ISSUE TITLE
Weird Highlighting after installing

### ISSUE THREAD

**Issue by Entraff** [neoclide/coc.nvim#3217]
## versions

vim version: NVIM v0.4.4
node version: v16.3.0
coc.nvim version: 0.0.80-aa24232066
coc.nvim directory: /home/thomas/.vim/plugged/coc.nvim
term: xterm-kitty
platform: linux

## Log of coc.nvim

2021-07-13T15:46:04.484 INFO (pid:16105) [plugin] - coc.nvim 0.0.80-aa24232066 initialized with node: v16.3.0 after 153ms
2021-07-13T15:46:04.497 INFO (pid:16105) [services] - registered service "clangd"
2021-07-13T15:46:04.497 INFO (pid:16105) [services] - clangd state change: stopped => starting
2021-07-13T15:46:04.502 INFO (pid:16105) [language-client-index] - Language server "clangd" started with 16115
2021-07-13T15:46:04.527 INFO (pid:16105) [services] - clangd state change: starting => running
2021-07-13T15:46:04.534 INFO (pid:16105) [services] - service clangd started
2021-07-13T15:46:12.465 INFO (pid:16105) [attach] - receive notification: showInfo []
2021-07-13T15:46:58.089 INFO (pid:16105) [completion-complete] - Results from: around,clangd
2021-07-13T15:47:06.588 INFO (pid:16105) [completion-complete] - Results from: clangd
2021-07-13T15:47:14.498 INFO (pid:16105) [attach] - receive notification: showInfo []
2021-07-13T15:47:41.066 INFO (pid:16105) [attach] - receive notification: showInfo []

## Describe the bug

Whenever writing a program (specifically C/C++), coc.nvim seems to provide additional syntax highlighting after a second of not writing anything, but doesn't appear to be very consistent. At times it even looks random what it chooses to highlight, where it stops highlighting mid-word. The additional highlighting sometimes even disappears altogether.

## Reproduce the bug

Install coc.nvim with vim-plug
```vim
Plug 'neoclide/coc.nvim', {'branch': 'release'}
```
Run `:CocInstall coc-clangd`

Use the following .vimrc setup

```vim
set nocompatible
set runtimepath^=/path/to/coc.nvim
filetype plugin indent on
syntax on
set hidden
```

Open any C/C++ file.

## Screenshots (optional)

Syntax Highlighting without coc.nvim being added to the runtimepath in the .vimrc above

![2021-07-13-153213_442x532_scrot](https://user-images.githubusercontent.com/70814063/125513975-39c2c40d-de00-4353-a5fd-942cf3b03af1.png)

Syntax Highlighting with coc.nvim added to the runtimepath after waiting a second when opening a file

![2021-07-13-153034_440x537_scrot](https://user-images.githubusercontent.com/70814063/125514145-824e8caf-2289-449d-8cd3-7404b53d5ff4.png)

Syntax Highlighting with coc.nvim added to the runtimepath adding a few lines of code

![2021-07-13-153110_451x596_scrot](https://user-images.githubusercontent.com/70814063/125514215-33f8e05b-1e5e-4088-8eb1-06ade3ad7457.png)

**Comment by Alexey104** [comment]
Are you using clangd?
https://github.com/clangd/coc-clangd/issues/298#issue-941224538

**Comment by pmsanford** [comment]
I'm getting the same thing with `coc-rust-analyzer`. I used git bisect to narrow it down, and this commit is the first one where this occurs: https://github.com/neoclide/coc.nvim/commit/804a007033bd9506edb9c62b4e7d2b36203ba479 Running on any commit before that produces the expected highlighting. I'm running neovim 0.5, but saw the same thing on another machine with 0.4 as well.

**Comment by pmsanford** [comment]
Here's what happens running on commit https://github.com/neoclide/coc.nvim/commit/804a007033bd9506edb9c62b4e7d2b36203ba479 (the first commit where this behavior occurs)
![bad-highliting](https://user-images.githubusercontent.com/1696007/125529818-f4dea893-e18a-4e22-9136-2c9c640e386c.gif)

Here's what happens running on the commit before that (https://github.com/neoclide/coc.nvim/commit/891d1687ac3aa8ae2c5d92cb5cf0bb8c736bf0f1), which is the previous and expected behavior for me:
![good-highlighting](https://user-images.githubusercontent.com/1696007/125529861-b4dd5233-d77a-44ac-9481-08db4f321839.gif)

**Comment by oblitum** [comment]
@pmsanford What you're pointing **is not an issue**, it's just semantic highlight that gets active by default, but can only happen after rust-analyzer finishes its code analysis, which takes some time on startup, but should be faster afterwards while in the same session. Semantic highlight overrides tree-sitter/standard highlight. You can either customize the highlighting groups or disable the feature through `g:coc_default_semantic_highlight_groups = 0`.

The actual issue that exists is provided by OP where highlighting gets clobbered after some edits and stays clobbered afterwards. I only saw that happening with clangd, didn't see it happen with rust-analyzer yet.

**Comment by oblitum** [comment]
There's some issue duplication happening:

- #3175
- https://github.com/clangd/coc-clangd/issues/298

**Comment by pmsanford** [comment]
@oblitum ah, that makes sense. Sorry for the noise.

**Comment by oblitum** [comment]
@pmsanford it may look better with other colorschemes or after tweaking the groups, it's more featureful than what tree-sitter has to offer ;)

**Comment by Entraff** [comment]
> @pmsanford What you're pointing **is not an issue**, it's just semantic highlight that gets active by default, but can only happen after rust-analyzer finishes its code analysis, which takes some time on startup, but should be faster afterwards while in the same session. Semantic highlight overrides tree-sitter/standard highlight. You can either customize the highlighting groups or disable the feature through `g:coc_default_semantic_highlight_groups = 0`.
> 
> The actual issue that exists is provided by OP where highlighting gets clobbered after some edits and stays clobbered afterwards. I only saw that happening with clangd, didn't see it happen with rust-analyzer yet.

Disabling the semantic highlighting is what I have been looking for, thank you. However, I am still confused on why such a thing would happen regarding the highlighting getting messed up.

**Comment by oblitum** [comment]
> However, I am still confused on why such a thing would happen regarding the highlighting getting messed up.

@Entraff despite being sufficient for you to simply disable it, the reported issue still exists.

**Comment by Entraff** [comment]
> > However, I am still confused on why such a thing would happen regarding the highlighting getting messed up.
> 
> @Entraff despite being sufficient for you to simply disable it, the reported issue still exists.

You are correct. I will reopen the issue.

**Comment by therealdannzor** [comment]
Ah, at least this issue officially acknowledged. This has been bugging me for two days now, "happy" to see that I'm not alone. I believe I have the same problem.

Expected colour:
![before_finishes_loading](https://user-images.githubusercontent.com/35889839/125760575-f8d9f81d-1d73-424b-8322-317528335adc.png)

Actual colour: 
![nvim_0-5-0_onedark](https://user-images.githubusercontent.com/35889839/125760562-efef4232-a78d-453d-a48b-b1c969a58bcb.png)

**Comment by oblitum** [comment]
All the fuzz happening is the reason I asked [consideration regarding default ON or OFF](https://github.com/neoclide/coc.nvim/pull/3186#issuecomment-874743289). Kinda expected...

**Comment by chemzqm** [comment]
The semantic highlight feature need some rework, and it's confusing when we add the highlights by default.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

**Comment by GiuseppeCesarano** [comment]
I updated coc and since the default colors where disabled i assigned a color to each highlight group, i still get the weird behavior that happens from [picture 2](https://user-images.githubusercontent.com/70814063/125514145-824e8caf-2289-449d-8cd3-7404b53d5ff4.png) to [picture 3](https://user-images.githubusercontent.com/70814063/125514215-33f8e05b-1e5e-4088-8eb1-06ade3ad7457.png) after an edit

**Comment by Alexey104** [comment]
Confirm.

**Comment by alexfrederiksen** [comment]
Same can we reopen this?

**Comment by oblitum** [comment]
There's no need to reopen since this issue won't happen by default anymore. Please open another issue requesting a fix for when the feature is explicitly enabled, and if possible describe behavior on multiple servers, like, clangd and rust-analyzer.
