### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by gpanders** [neoclide/coc.nvim#325]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.
`Not an editor command: CocInfo`

**Describe the bug**
On Neovim startup, I get the following error:
```vim
[vim-node-coc]: Plugin initialized error: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Extensions.get globalExtensions [as globalExtensions] (/snapshot/coc.nvim/lib/extensions.js:565:23)
    at Extensions.globalExtensionStats (/snapshot/coc.nvim/lib/extensions.js:520:26)
    at Extensions.init (/snapshot/coc.nvim/lib/extensionp
```

**To Reproduce**

1. Install latest coc.nvim
2. Start neovim

**Steps Taken**
I have completely removed the coc.nvim package folder as well as all installed yarn dependencies and reinstalled. The error persists.

This is how I'm installing coc.nvim (using minpac):

```vim
call minpac#add('neoclide/coc.nvim', {'rev': "v0.0.45', 'do': 'call coc#util#install()'})
```

**Comment by chemzqm** [comment]
Try install a coc extension like `:CocInstall coc-json` should fix this problem.
It's caused by invalid package.json file that created on install.

**Comment by gpanders** [comment]
I did `:CocInstall coc-json` and `:CocInstall coc-pyls`. That did not solve the problem.

**Comment by chemzqm** [comment]
Looks like your package.json is broken, please paste the content from `:exe 'edit '.coc#util#extension_root().'/package.json'`

**Comment by gpanders** [comment]
`~/.config/coc/extensions/package.json`:
```json
{}
```
