### ISSUE TITLE
Quirky behavior of the variable coc_disabled_sources

### ISSUE THREAD

**Issue by z0xyz** [neoclide/coc.nvim#3734]
## versions

vim version: VIM - Vi IMproved 8.2 8023458
node version: v17.8.0
coc.nvim version: 0.0.80-3dc25e03 2022-03-29 23:12:08 +0800
coc.nvim directory: /home/sinful/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2022-03-31T00:50:28.877 INFO (pid:13352) [plugin] - coc.nvim initialized with node: v17.8.0 after 130ms
2022-03-31T00:50:34.800 INFO (pid:13352) [attach] - receive notification: showInfo []

## Describe the bug

I wanted to disable buffer completions, and only stick to the dictionary words at text files. Therefor i tried setting `let b:coc_disabled_sources = ['around', 'buffer' , 'file']` It's rather quirky i.e. let's say for any buffer of filetype text, i set the variable in this way . When i open a text file, and input a forward slash character, it still shows path completions, but it only allows tabbing, without substring matching of the available completions. The same behavior applies for every other disabled source. Meaning that they show up when their trigger character is inputted, but they only allow tabbing . 

## Minimal vimrc
```
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

let g:coc_global_extensions = [
    \'coc-json',
    \'coc-snippets',
    \'coc-sh',
    \'coc-python',
    \'coc-tsserver',
    \'coc-html',
    \'coc-css',
\ ]
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
if exists('*complete_info')
	inoremap <silent><expr> <cr> complete_info(['selected'])['selected'] != -1 ? "\<C-y>" : "\<C-g>u\<CR>"
endif
"Move towards the next placeholder within a snippet
let g:coc_snippet_next = '<tab>'
" Enable coc-nvim per file type
function! s:disable_coc_for_type()
    "let l:filesuffix_blacklist = ['txt']
	"if index(l:filesuffix_blacklist, expand('%:e')) != -1
    let l:filetype_blacklist = ['text']
    if index(l:filetype_blacklist, &filetype) != -1
        let b:coc_disabled_sources = ['around', 'buffer' , 'file']
	endif
endfunction
autocmd BufRead,BufNewFile * call s:disable_coc_for_type()

set dictionary=/usr/share/dict/american-english

**Comment by chemzqm** [comment]
Should be fixed by 816dbd31

**Comment by z0xyz** [comment]
Thanks! it did work. However the delay still persists. As aforementioned i was trying to disable buffer completions and only work with dictionary completions. However when i open a vacant file dictionary completions works just fine without delay, but with other large prose file, it does delay.

**Comment by chemzqm** [comment]
> it does delay.

What kind of delay?

**Comment by z0xyz** [comment]
If i open a vacant file and another one bloated with data and miscellaneous content, then the latter would delay before dictionary word completions, while the former would show them with the typical speed.

**Comment by z0xyz** [comment]
I should also mention that i've just noticed that the delay scale up according to the buffer size. so if the file contains more content, so does the delay. What i deduced from that, is the fact that even with the buffer source being turned off, it still somehow interferes with completions (which is the dictionary in this case)

**Comment by chemzqm** [comment]
It's optimized, check your coc.nvim version by `:CocInfo`

**Comment by z0xyz** [comment]
I don't if i understand what you're referring to correctly , but i've already listed it at the top of the current thread. But that's the output back again.

```
vim version: VIM - Vi IMproved 8.2 8023458
node version: v17.8.0
coc.nvim version: 0.0.80-d0ba54c9 2022-03-30 18:45:24 +0800
coc.nvim directory: /home/sinful/.vim/plugged/coc.nvim
term: dumb
platform: linux
```

**Comment by z0xyz** [comment]
@chemzqm any updates ? the same behavior is still persistent.

**Comment by chemzqm** [comment]
No, I don't know how to reproduce the delay you have mentioned.

**Comment by z0xyz** [comment]
I've reproduced by yanking the textual content of this [novel](https://www.ccel.org/ccel/c/calvin/calcom31/cache/calcom31.txt) multiple times at a buffer, then disable buffer completions for it, but with the dictionary enabled (English dictionary).
The expected behavior 
snappy autocompletion as the completions are only reliant on the dictionary words (not the buffer)
What happens
The completions delay significantly.

**Comment by chemzqm** [comment]
What dictionary your're using?

**Comment by z0xyz** [comment]
The American English dictionary located at `/usr/share/dict/american-english`

**Comment by chemzqm** [comment]
It is slow when editing big buffer with coc.nvim, which caused by the slow diff algorithm.
It that the delay you have mentioned?

**Comment by z0xyz** [comment]
> It is slow when editing big buffer with coc.nvim

Indeed, yes.

> by the slow  diff algorithm.

Just a side question , is there a chance for a better algorithm to handle it?

**Comment by chemzqm** [comment]
Sure, it should be fixed.

**Comment by z0xyz** [comment]
Thanks! Please don't forget me to notify me at the current thread when a patch/fix is added, so that i can get the chance to give my take on its performance.

**Comment by chemzqm** [comment]
It's optimized.

**Comment by z0xyz** [comment]
Just updated, and noticed that the first complaint concerning `let b:coc_disabled_sources = ['around', 'buffer']` is still existent. Let's say with this variable set, i opened two text files. The first one is vacant, i would type just fine with no cpu spikes or subtle stutter or anything... just flawless. On the contrary, the other file -which is full of text and content- would get the cpu spikes and stutter a bit. I found out that it has to do with  with my autocommand, but i can't figure out why!
```
function! s:disable_coc_for_type()
    let g:filetype_blacklist = ['text']
    if index(g:filetype_blacklist, &filetype) != -1
        let b:coc_disabled_sources = ['around', 'buffer']
    endif
endfunction
autocmd BufRead,BufNewFile * call s:disable_coc_for_type()
```

As for the optimization, i really want thank you for the work being done! it's more prompt and less cpu intensive now with large files. Still, It only has few drawbacks
* there's still a bit of cursor stutter, especially with fast typing (though not as much as it used to be).
* backspacing stutters even more.
* CPU spikes got reduced from averaging 50% to around 20/30% while typing.
There's an overall notable enhancement, but still not as flawless, but this is completely understandable as js isn't an interpreted language. I'm sure that if you enhancement was applied to a compiled one, then it would've been seamless.

**Comment by chemzqm** [comment]
It's slower on vim8, since coc have to fetch all buffer lines from vim on TextChange

**Comment by z0xyz** [comment]
How about the autocommand? It firstly didn't work, got fixed, but now it seems to be still have the aforementioned culprit.

**Comment by z0xyz** [comment]
@chemzqm I can't really tell if it has something wrong to do with my setup or what, but after couple updates of the plugin, the problem still persists.

**Comment by chemzqm** [comment]
I can't reproduce, please fill issue template.

**Comment by z0xyz** [comment]
My bad. when i came to reproduce, i found that i forgot to enable it back.

**Comment by chemzqm** [comment]
Need the detailed steps to reproduce.

polendina ***@***.***> 于2022年4月1日周五 10:19写道：
