### ISSUE TITLE
`pyls` work under  **win10** when writing python

### ISSUE THREAD

**Issue by leoatchina** [neoclide/coc.nvim#52]
**Describe the bug**
`pyls` work under  **win10** when writing python, the minimal vimrc is
```
if has('nvim') && v:version >=800 && executable('node') && executable('yarn')
    if WINDOWS()
        Plug 'neoclide/coc.nvim', {'do': '.\\install.cmd'} 
    else
        Plug 'neoclide/coc.nvim', {'do': './install.sh'}
    endif
endif
```
 - I have already  `pip3 install python-language-server[all]`, `neosnippet` is  also installed for no `+python` or `+python3` feature, the `NS` snippet appeared in popup menu. 

 - This plugins works in centos, ubuntu, mac, but not windows.

 -  Acutally  I have changed the complete_engine to `asyncomplete` ,  and configed my vimrc according to its REAME,  `pyls` works when do  python writing.

**To Reproduce**
For example , type these  below
```
import os
os.path.isfile()
```
The **path**, or **isfile** should appear in popup menu after type in `.` since it is the standard libray, but not.

**Screenshots**
Forget to capture, put it on later

**Desktop (please complete the following information):** 
 - Version: neovim-qt 0.3.1 32/64bit,  python3.7-64bit,  node.js 8.11.4(msi) , yarn 1.9.4(msi), windows10_1709/1803

**Comment by chemzqm** [comment]
Could you attach the log of `pyls`?  The log could be enabled by set
```
  "languageserver": {
     "pyls": {
        "trace.server": "verbose",
     }
   }
```
in coc-setting.json opened with `:CocConfig` command.

Make the error happen and open the log buffer with `:CocAction('runCommand', 'workspace.showOutput')`

**Comment by leoatchina** [comment]
I have `:CocConfig`, but  when `:CocAction`
![default](https://user-images.githubusercontent.com/4470821/44259600-8f45eb00-a244-11e8-92b9-3693b360d44f.png)

**Comment by fannheyward** [comment]
@leoatchina `:call CocAction('runCommand', 'workspace.showOutput')` instead.

**Comment by leoatchina** [comment]
[coc.log](https://github.com/neoclide/coc.nvim/files/2296763/coc.log)
Upload the log

**Comment by chemzqm** [comment]
It should be cause by slow of language server, I've improved document change event, so this problem should be fixed.

**Comment by leoatchina** [comment]
Still not work for python in windows, but works good writing ts, js, etc
