### ISSUE TITLE
Popup doesn't clear after itself.

### ISSUE THREAD

**Issue by iamemhn** [neoclide/coc.nvim#5334]
## Result from CocInfo

    1 ## versions                                                               
    2                                   
    3 vim version: VIM - Vi IMproved 9.0 9002142
    4 node version: v20.19.1            
    5 coc.nvim version: 0.0.82-1baa8dcb 2025-05-05 17:08:59 +0800
    6 coc.nvim directory: /home/emhn/.vim/plugged/coc.nvim
    7 term: dumb 
    8 platform: linux
    9  
   10 ## Log of coc.nvim                
   11  
   12 2025-05-06T10:56:20.494 INFO (pid:293872) [plugin] - coc.nvim initialized       with node: v20.19.1 after 101     
   13 2025-05-06T10:56:23.597 INFO (pid:293872) [attach] - receive notification:       showInfo []

## Describe the bug

Open a new file. Type any word, e.g. `magic`, hit ENTER. Start typing `mag` . The autocompletion overlay appears showing `magic`. Completing to `magically`, hitting ENTER, or hitting backspace, leave the overlay on top. Moving around in the document will leave the overlay there.

This happens with *any* completion overlay (text, file name, language server...).

The issue started after I updated CoC on Monday around 2025-05-05 16:00 UTC

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)

I'll attach a GIF.

![Image](https://github.com/user-attachments/assets/25bd305c-0736-4d0c-a179-a6179a046df8)

**Comment by iamemhn** [comment]
It also happens with `gvim`

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc.nvim/issues/5333

This should be fixed already.

**Comment by iamemhn** [comment]
It's still happening on a fresh install of Coc

emhn@trillian:~/.vim/plugged/coc.nvim$ git log | head -5
commit 89226ea7f1c16db12edce9a7f6fc4076bc162df7
Author: Qiming Zhao <chemzqm@gmail.com>
Date:   Mon May 5 17:10:44 2025 +0800

    commit 1baa8dcb09ee427573aba665807e3f757659f98b

Is there a new commit that I'm still not seeing in the repo?

**Comment by iamemhn** [comment]
> [#5333](https://github.com/neoclide/coc.nvim/issues/5333)
> 
> This should be fixed already.

I did a fresh CoC install and can still reproduce it.

**Comment by fannheyward** [comment]
This fix hasn't been pushed to `release` branch, you can try the master branch or waiting for the CI to publish it.

**Comment by chemzqm** [comment]
I've updated release branch, this issue should be fixed.

**Comment by iamemhn** [comment]
I've updated to `release` a few minutes ago

```
commit 82a4676f76962d7380abdf9f166d0730d985ca79 (HEAD -> release, origin/release)
Author: Qiming Zhao <chemzqm@gmail.com>
Date:   Wed May 7 16:06:52 2025 +0800
```

and things are working as expected. Thanks!
