### ISSUE TITLE
vim-node-coc: Crypto deprecation warning

### ISSUE THREAD

**Issue by delfick** [neoclide/coc.nvim#625]
**Result from CocInfo**

```
## versions

vim version: NVIM v0.3.4
node version: v8.9.0
coc.nvim version: 0.0.64
term: iTerm.app
platform: darwin

## Error messages
(node:56171) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:56171) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.

```

**Describe the bug**

When I open up neovim it shows these two messages

```
[vim-node-coc]: (node:56171) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
[vim-node-coc]: (node:56171) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
```

**To Reproduce**

Can be reproduced with the suggested mini.vim.

I'm running nodejs v10.13.0

**Comment by chemzqm** [comment]
You're using binary release, checkout https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-to-use-cocnvim-from-master-branch for use coc.nvim from master branch.

This warning should not exists with master branch.

**Comment by delfick** [comment]
Yeap, seems fixed in master :)

**Comment by chemzqm** [comment]
It's not fixed, it's because `--no-warnings` is used when using your node.

**Comment by delfick** [comment]
right, that's kinda hilarious
