### ISSUE TITLE
[coc.nvim] error: Uncaught exception: Error: EACCES: permission denied, open '/tmp/node-client.log'

### ISSUE THREAD

**Issue by mvrozanti** [neoclide/coc.nvim#800]
## Result from CocInfo
`:CocInfo`:
```
## versions

vim version: NVIM v0.3.4
node version: v11.13.0
coc.nvim version: 0.0.67-f9652d2f59
term: screen-256color
platform: linux

## Error messages
```

## Describe the bug

vim starts with the following status bar error message: `[coc.nvim] error: Uncaught exception: Error: EACCES: permission denied, open '/tmp/node-client.log'`

When running `vim`, somehow this file (`/tmp/node-client.log`) is being created by Coc opening `~/.config/nvim/plugged/coc.nvim/build/index.js`. If vim is opened again but this time with sudo, I always get priviledge error. This also happens the other way around: deleting the file and then running `sudo vim` shows no error message on startup, but starting vim right after as a normal user makes the message appears.

## Reproduce the bug

I get this error with only:

1.  Create file `mini.vim` with：

  ```vim
set nocompatible
set runtimepath^=/home/nexor/.config/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
  ```

2. Start neovim with command: `vim -u mini.vim`
- `/tmp/node-client.log` is created
3. Start neovim with command: `sudo vim -u mini.vim`
- Error message appears

**Comment by mvrozanti** [comment]
It doesn't appear to have any other side effect than being really annoying

**Comment by mvrozanti** [comment]
Upon trying to `:CocUpdate` I also noticed the following output:

```
yarn upgrade v1.15.2
warning package.json: No license field
warning No license field
warning No license field
warning No license field
[1/4] Resolving packages...
warning coc-python > os-tmpdir@2.0.0: This is not needed anymore. `require('os').tmpdir()` in Node.js 4 and up is good.
[2/4] Fetching packages...
[3/4] Linking dependencies...
error An unexpected error occurred: "EACCES: permission denied, unlink '/home/nexor/.config/coc/extensions/node_modules/buffer-alloc/index.js'".
info If you think this is a bug, please open a bug report with the information provided in "/home/nexor/.config/coc/extensions/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.

[Process exited 1]
```

**Comment by mvrozanti** [comment]
tried using `sudo chown -R $(whoami) `, now I get no messages after `:CocUpdate`. Not sure if it worked either

**Comment by mvrozanti** [comment]
I just learned I shouldn't be using `sudo vim` and that might just be the problem after all

**Comment by jamespharvey20** [comment]
FYI, this is fixed in more recent commits.  i.e. fb5f17a makes the new filename `coc-nvim-${process.pid}.log`, so there won't be permissions conflicts.

**Comment by mvrozanti** [comment]
I'm at 3ebf5f but am still getting the error on the same file.

**Comment by chemzqm** [comment]
Change your `NODE_CLIENT_LOG_LEVEL` environment variable to default value `info`

**Comment by jamespharvey20** [comment]
@mvrozanti you're right, sorry about that.  Looks like there are a few more places that don't guarantee unique tempfile names.  There's:

* `neoclide/coc.nvim::src/attach.ts::12`

      const nvim: NeovimClient = attach(opts, log4js.getLogger('node-client'), requestApi)

* `chemzqm/node-client::src/utils/logger.ts::11`

        const LOG_FILE_PATH = process.env.NVIM_COC_LOG_FILE || path.join(os.tmpdir(), 'node-client.log')

* `neoclide/coc.nvim::src/util/logger.ts::17`

          let linkfile = path.join(os.tmpdir(), 'coc-nvim.log')

* `neoclide/coc.nvim::src/util/logger.ts::52` (I think)

        module.exports = (name = 'coc-nvim'): log4js.Logger => {
