### ISSUE TITLE
Can't use :CocInstall

### ISSUE THREAD

**Issue by Leeshe** [neoclide/coc.nvim#922]
## Result from CocInfo

```vim
## versions

vim version: NVIM v0.4.0-762-g9420a2127
node version: v8.10.0
coc.nvim version: 0.0.71
term: xterm-256color
platform: linux

## Messages
[coc.nvim] Install coc-pairs error: Unexpected token d in JSON at position 0
```

## Describe the bug

When using `:CocInstall coc-pairs`, I got the above error.

## Reproduce the bug

Same happens with minimal config.

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

**Comment by chemzqm** [comment]
Could be network issue, or you're using very old npm.

**Comment by Leeshe** [comment]
Thanks for the help, it was effectively npm, this fixed the issue: `npm install npm@latest -g`.

**Comment by morenoh149** [comment]
I get this error as well. Versions
```
$ npm -v
6.9.0
$ node -v
v12.1.0
```
using release branch
```
" Use release branch
Plug 'neoclide/coc.nvim', {'branch': 'release'}
```
using asdf for managing language version
```
$ asdf -v
version: v0.7.0
```

**Comment by chemzqm** [comment]
Shuld be fixed now.

**Comment by morenoh149** [comment]
still not working for me, I tried the release version and the source with yarn. Do you have to do something after `:PlugInstall` to get `:CocInfo` working in vim?

**Comment by chemzqm** [comment]
@morenoh149 If you don't have `:CocInfo`, it means your vim version is too low and the plugin won't load.

**Comment by morenoh149** [comment]
that was it. I was running
```
$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 22 2019 18:22:38)
Included patches: 1-503, 505-680, 682-1283
Compiled by root@apple.com
```
did
```
$ brew install vim
$ exec -l $SHELL
```
and now `:CocInfo` works.
