### ISSUE TITLE
Coc hides swap file message on file reload

### ISSUE THREAD

**Issue by trygveaa** [neoclide/coc.nvim#948]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  2 2019 20:06:04)
node version: v11.15.0
coc.nvim version: 0.0.72-4aee0cab77
term: dumb
platform: linux

## Messages
Messages maintainer: Bram Moolenaar <Bram@vim.org>
E325: ATTENTION
E325: ATTENTION
```

## Describe the bug

When you open a file which is already open by another vim process, you get a message saying a swap file exists and asking what to do. If you then reload the file by running `:e:`, you would normally get the same message again. However, when Coc is loaded, only "E325: ATTENTION" is shown, and the rest of the message doesn't appear. Vim is still waiting for you to select one of the actions, like when the message is shown though.

## Reproduce the bug

- Create file `mini.vim` with:

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start vim with command: `vim -u mini.vim test`

- Start another vim with command: `vim -u mini.vim test`

- Press `o` or `e` on the swap file message

- Run `:e`

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/601966/60709478-d0a0c100-9f10-11e9-81f5-5026ff69fcf6.png)

**Comment by chemzqm** [comment]
Don't know how to fix, it happens when channel send message to vim, my advice is use `set noswapfile` to disable swap file.

**Comment by chemzqm** [comment]
Just tried latest vim 8.1-1628, it was fixed.

**Comment by trygveaa** [comment]
Hm, I tried compiling v8.1.1635 now, and it still happens for me with that version.

I'm using the swapfile features, so I don't want to disable that.

**Comment by chemzqm** [comment]
No idea then, it shown as expect for me
<img width="668" alt="Screen Shot 2019-07-05 at 5 55 39 PM" src="https://user-images.githubusercontent.com/251450/60714692-2778bb80-9f4e-11e9-8648-0b74d7412572.png">

**Comment by trygveaa** [comment]
Hm, any tips on how to debug this?

The message is shown for you every time you reload the file with `:e`?

`:version` outputs this:
```
:version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  5 2019 11:51:29)
Included patches: 1-1635
Compiled by trygve@elaine
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +byte_offset       +conceal           -ebcdic            +folding           +keymap            +menu              +mouse_sgr         +packages          +quickfix          +startuptime       +terminal          +vartabs           +windows
+arabic            +channel           +cryptv            +emacs_tags        -footer            +lambda            +mksession         -mouse_sysmouse    +path_extra        +reltime           +statusline        +terminfo          +vertsplit         +writebackup
+autocmd           +cindent           +cscope            +eval              +fork()            +langmap           +modify_fname      +mouse_urxvt       -perl              +rightleft         -sun_workshop      +termresponse      +virtualedit       +X11
+autochdir         +clientserver      +cursorbind        +ex_extra          +gettext           +libcall           +mouse             +mouse_xterm       +persistent_undo   -ruby              +syntax            +textobjects       +visual            -xfontset
-autoservername    +clipboard         +cursorshape       +extra_search      -hangul_input      +linebreak         +mouseshape        +multi_byte        +postscript        +scrollbind        +tag_binary        +textprop          +visualextra       +xim
+balloon_eval      +cmdline_compl     +dialog_con_gui    -farsi             +iconv             +lispindent        +mouse_dec         +multi_lang        +printer           +signs             -tag_old_static    +timers            +viminfo           +xpm
+balloon_eval_term +cmdline_hist      +diff              +file_in_path      +insert_expand     +listcmds          +mouse_gpm         -mzscheme          +profile           +smartindent       -tag_any_white     +title             +vreplace          +xsmp_interact
+browse            +cmdline_info      +digraphs          +find_in_path      +job               +localmap          -mouse_jsbterm     +netbeans_intg     -python            +sound             -tcl               +toolbar           +wildignore        +xterm_clipboard
++builtin_terms    +comments          +dnd               +float             +jumplist          -lua               +mouse_netterm     +num64             -python3           +spell             +termguicolors     +user_commands     +wildmenu          -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/home/trygve/vim-install/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/freetype2
-I/usr/include/libpng16 -I/usr/include/uuid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/atk-1.0 -pthread    -O2 -fno-strength-reduce -Wall -D_REENTRANT  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl
  -lcanberra  -lacl -lattr -lgpm -ldl
```

**Comment by chemzqm** [comment]
It's not shown on `:e!`, but work as expected on neovim, don't know how to fix.

**Comment by trygveaa** [comment]
Thanks, that fixed it!

**Comment by trygveaa** [comment]
Unfortunately, this issue has appeared again after commit 4fe01e0597e4b4a52a3216c7a363fa5396d5e217.

**Comment by chemzqm** [comment]
@trygveaa Can't reproduce, do you have `tag: '*'` with Plug command?

**Comment by trygveaa** [comment]
No, should I?

**Comment by trygveaa** [comment]
Steps to reproduce:
1. `mini.vim`:
```
set nocompatible
set runtimepath^=~/.vim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
```
2. Run `vim -u mini.vim test`
3. In the same directory, run `vim -u mini.vim`
4. In the last vim process, run `:e test`

`~/.vim/plugged/coc.nvim` is checked out at the release branch, commit 725569f.

**Comment by chemzqm** [comment]
Fixed with 533b3070
