### ISSUE TITLE
"magic" completions not working

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#961]
## versions

vim version: NVIM v0.4.0-1198-g0dc73b87f
node version: v11.15.0
coc.nvim version: 0.0.72
term: tmux-256color
platform: linux

## Output channel: watchman

[Info  - 5:50:17 AM] watchman watching project: /home/francisco/Projects/samples/rust
[Info  - 5:50:17 AM] subscribing "**/.eslintr{c.js,c.yaml,c.yml,c,c.json}" in /home/francisco/Projects/samples/rust
[Info  - 5:50:17 AM] subscribing "**/.eslintignore" in /home/francisco/Projects/samples/rust
[Info  - 5:50:17 AM] subscribing "**/package.json" in /home/francisco/Projects/samples/rust
[Info  - 5:50:17 AM] subscribing "**/{.prettierrc,.prettierrc.json,.prettierrc.yaml,.prettierrc.yml,.prettierrc.js,package.json,prettier.config.js}" in /home/francisco/Projects/samples/rust

## Output channel: snippets

[Info  - 5:50:17 AM] watchman watching project: /home/francisco/.config/coc/ultisnips
[Info  - 5:50:17 AM] subscribing "**/*.snippets" in /home/francisco/.config/coc/ultisnips

## Describe the bug

I [just came to learn](https://github.com/rust-analyzer/rust-analyzer/issues/1516) of "magic" completions supported by rust-analyzer that don't work with coc.nvim, but works on VSCode. What they are is explained [here](https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/features.md#magic-completions) and how they should behave can be viewed [in this video](https://www.youtube.com/watch?v=jNnvaHbnhK8&t=22).

## Reproduce the bug

- [Follow the wiki to install rust-analyzer](https://github.com/neoclide/coc.nvim/wiki/Language-servers#rust)

- Create file `mini.vim` with：

  ```vim
  augroup vimrc | autocmd! | augroup end

  if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    autocmd vimrc VimEnter * PlugInstall --sync | source $MYVIMRC
  endif

  call plug#begin('~/.vim/plugged')
  Plug 'tpope/vim-sensible'
  call plug#load('vim-sensible')
  Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}
  call plug#end()

  let g:coc_user_config = {
  \   'languageserver': {
  \     'rust': {
  \       'command': 'ra_lsp_server',
  \       'filetypes': ['rust'],
  \       'rootPatterns': ['Cargo.toml']
  \     }
  \   }
  \ }
  ```

- `cargo init foo && cd foo`

- Start (neo)vim with command: `nvim -u mini.vim src/main.rs`

- in `main` type `x.if` and expand the suggestion

**Comment by chemzqm** [comment]
Please provide output so I could understand how it works.

**Comment by oblitum** [comment]
I've linked video and explanation in "Describe the bug". For example, `x.if<confirm>` should expand to `if x {<cursor here>}`, but coc doesn't do that, like it's shown in the video in VSCode, it expands by appending the expansion after `x.`, so it becomes `x.if x {<cursor here>}`

**Comment by chemzqm** [comment]
Looks like that feature use custom command which requires extension support to work.

**Comment by oblitum** [comment]
OK. If you conclude that's the case you can close the issue as I don't have the inner knowledge whether it should be part of coc or not.

**Comment by oblitum** [comment]
Current behavior is bad though, since coc provides a behavior for these snippets, but it provides incorrect expansions. It would be ideal if they weren't at all provided, or provided but working.

**Comment by chemzqm** [comment]
The language server should provide an option to disable feature, or check if it can be done with the client.

**Comment by oblitum** [comment]
OK. I'll report it back there.

**Comment by matklad** [comment]
@chemzqm that’s not a custom command, that is snippet completion (see insertTextFormt in https://microsoft.github.io/language-server-protocol/specification#textDocument_completion).

It’s true that the server should only send snippets if the client explicitly advertised support for them, but it should also be cool if coc.nvim supported snippets, they are a powerful feature! Though, IIRC, all vim plugins have trouble with non-trivial completions, so this might be a won’t fix due to some vim internal limitation.

**Comment by chemzqm** [comment]
coc.nvim has full support for snippet of LSP, need verbose output from language server to understand why it's not work as expected.

**Comment by matklad** [comment]
If this is helpful, here are the logs I get from VS Code:

https://gist.github.com/matklad/d12ae81f18766c80f56727f2d848fc0a

A specific `CompletionItem` looks like this:

```
{
        "additionalTextEdits": [
            {
                "newText": "",
                "range": {
                    "end": { "character": 7, "line": 1 },
                    "start": { "character": 4, "line": 1 }
                }
            }
        ],
        "detail": "match expr {}",
        "filterText": "match",
        "insertTextFormat": 2,
        "label": "match",
        "textEdit": {
            "newText": "match 92 {\n    ${1:_} => {$0\\},\n}",
            "range": {
                "end": { "character": 10, "line": 1 },
                "start": { "character": 7, "line": 1 }
            }
        }
}
```

**Comment by oblitum** [comment]
[This is the full output from coc.nvim](https://gist.github.com/oblitum/8a993a7c2212ffde6e580d11c3d9536a).

**Comment by chemzqm** [comment]
Should be bug of overlap range check for `additionalTextEdits` and `textEdit`

**Comment by oblitum** [comment]
OK looks fixed on b24601e, thx :)

**Comment by oblitum** [comment]
Just noticed that some expansions are not putting the cursor in the right place, for example, `x.match` expands snippets and puts the cursor correctly in the middle of the expression, but `x.if` expansion is not doing that, it's putting the cursor after the expression, not inside the `if`'s  body, same for `x.into`.

**Comment by chemzqm** [comment]
Position need fix plain text snippet https://github.com/neoclide/coc.nvim/blob/master/src/languages.ts#L609

**Comment by chemzqm** [comment]
Fixed

**Comment by oblitum** [comment]
@chemzqm behavior is still the same for me, though I ignore whether positions are in fact correct coming from rust-analyzer snippets when using VS Code (cc @matklad):

![screencast](https://user-images.githubusercontent.com/1269815/60994787-8e6beb00-a327-11e9-866c-ea8fc1e7778b.gif)

**Comment by oblitum** [comment]
I suspect repositioning is wrong when the snippet is single line, and text edits that remove text while expanding, happens on that line. Maybe that's why `x.match` expansion position is correct, but `x.if` and `x.box` are not, it gets lost positioning on the line where text is removed and added.

**Comment by oblitum** [comment]
Reopening as it doesn't seem fixed.

**Comment by chemzqm** [comment]
Please paste output from language server.

**Comment by oblitum** [comment]
@chemzqm my bad, it's expanding correctly in minimal `.vimrc`, there should be now some bad interaction with another plugin. I'll check which one is this.

**Comment by oblitum** [comment]
The plugin conflicting with coc.nvim expansion is [vim-matchup](https://github.com/andymass/vim-matchup). For some reason having it cause bad expansion like in the gif above.

**Comment by lucypero** [comment]
I'm sorry but how am I supposed to trigger the completions? `<cr>` doesn't work.
